In [3]:
import numpy as np

In [5]:
arrange_array2 = np.arange(0,10,2)
print(arrange_array2)

[0 2 4 6 8]


In [7]:
linspace_array = np.linspace(0,10,5)
print(linspace_array)

[ 0.   2.5  5.   7.5 10. ]


In [10]:
diag_matrix = np.diag([1,2,3])
print(diag_matrix)

diag_elements = np.diag(np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
))
print(diag_elements)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1 5 9]


In [12]:
eye_matrix = np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
eye_matrix_3x4 = np.eye(3, 4)
print(eye_matrix_3x4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [14]:
eye_matrix_k1 = np.eye(3, k=1)
print(eye_matrix_k1)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [16]:
import numpy as np
# 创建一个3x3的数组
arr = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
# 使用.T属性进行转置
arr_T = arr.T
print(arr_T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [28]:
arr = np.arange(6)

arr_reshaped = arr.reshape((2, 3))
print(arr_reshaped)

[[0 1 2]
 [3 4 5]]


In [29]:
import numpy as np

# 创建一个二维数组
arr = np.array([[1, 2, 3], [4, 5, 6]])

# 使用flatten转换为一维数组
arr_flat = arr.flatten()  # 注意：这里也可以直接使用 np.flatten(arr)，但使用数组对象的方法更常见

print(arr_flat)
# 输出:
# [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [31]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

c = np.concatenate((a,b),axis=0)  # 沿着第0轴（行）连接
print(c)

d = np.concatenate((a,b.T),axis=1)  # 沿着第1轴（列）连接
print(d)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [35]:
a = np.array([1,2])
b = np.array([3,4])

# 沿着新的轴堆叠
c = np.stack((a,b),axis=0)  # 沿着第0轴堆叠
print(c)

d = np.stack((a,b),axis=1)  # 沿着第1轴堆叠
print(d)

e = np.concatenate((a,b), axis=0)  # 沿着第0轴连接
print(e)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3 4]


In [36]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.vstack((a, b))
print(c)
# 输出:
# [[1 2]
#  [3 4]]


[[1 2]
 [3 4]]


In [37]:
a = np.array([[1], [2]])
b = np.array([[3], [4]])
c = np.hstack((a, b))
print(c)
# 输出:
# [[1 3]
#  [2 4]]


[[1 3]
 [2 4]]


In [38]:
a = np.array([1, 2, 3, 4, 5])

#删除值为3的元素
mask = a != 3
print(mask)
b = a[mask]
print(b)


[ True  True False  True  True]
[1 2 4 5]


In [1]:
import numpy as np

A = np.array([1, 2, 3])  # 形状 (3,)
B = np.array([10, 20, 30, 40])  # 形状 (4,)

# 尝试进行加法运算，但直接相加会报错，因为形状不匹配
# 但如果我们将A视为 (1, 3) 形状的数组，并将B视为 (4, 1) 形状的数组，然后进行逐元素加法，则可以实现广播
# 然而，NumPy不会直接显示地改变数组的形状，而是隐式地进行广播

# 实际上，NumPy不允许直接将形状为 (3,) 和 (4,) 的数组进行广播
# 但如果我们将B的前三个元素与A的元素相加，可以模拟广播的效果（注意：这不是NumPy的默认行为）
# 为了演示广播，我们可以使用形状兼容的数组
C = np.array([10, 20, 30])  # 形状 (3,)
D = A + C  # 这里可以广播，因为形状相同
print(D)  # 输出: [11 22 33]

# 注意：上面的C和D的示例是为了说明广播的概念，而不是NumPy直接允许的操作


[11 22 33]


In [2]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])  # 形状 (2, 3)
B = np.array([10, 20, 30])  # 形状 (3,)

# B会被视为形状为 (1, 3) 的数组，然后在第一个维度上复制以匹配A的形状 (2, 3)
# 现在A和B具有相同的“广播后”形状，可以进行逐元素加法
C = A + B
print(C)
# 输出:
# [[11 22 33]
#  [14 25 36]]


[[11 22 33]
 [14 25 36]]


In [7]:
arr1 = np.random.rand(5)
print(arr1)

arr2 = np.random.rand(2,3)
print(arr2)

[0.66309783 0.7948689  0.55487851 0.95227315 0.87951584]
[[0.10049459 0.42606765 0.98969052]
 [0.68770203 0.95519184 0.53872093]]


In [8]:
import numpy as np

# 生成一个具有5个元素的一维数组
arr1 = np.random.randn(5)
print(arr1)

# 生成一个2行3列的二维数组
arr2 = np.random.randn(2, 3)
print(arr2)


[-1.5080315  -0.42491158  1.37995143 -0.52816624 -0.50529157]
[[-1.15799049  0.76681092 -0.99189644]
 [-0.34064741  0.44910401  0.63818713]]


In [10]:
import numpy as np

# 生成一个在[1, 10)之间的一维整数数组
arr1 = np.random.randint(1, 10, size=5)
print(arr1)

# 生成一个在[1, 10)之间2行3列的二维整数数组
arr2 = np.random.randint(1, 10, size=(2, 3))
print(arr2)

[7 6 3 6 3]
[[9 7 5]
 [5 4 6]]


In [13]:
import numpy as np

# 生成一个在[1, 5)之间的一维数组
arr1 = np.random.uniform(1, 5, size=5)
print(arr1)

# 生成一个在[1, 5)之间2行3列的二维数组
arr2 = np.random.uniform(1, 5, size=(2, 3))
print(arr2)

[4.76148493 2.95934877 3.7242065  2.00616413 4.40270985]
[[3.33201881 3.23810554 4.45104286]
 [4.88306576 1.84445888 4.65124523]]
