In [3]:
import numpy as np

arr=np.array([1, 2, 3, 4, 5])

for i in arr:
    print(i)

1
2
3
4
5


In [7]:
import numpy as np

# 定义两个向量
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 计算数量积
#dot_product = np.dot(a, b)
dot_product = a @ b

print("数量积为：", dot_product)  # 输出: 数量积为： 32

数量积为： 32


In [8]:
arr = np.array([1,2,3,4,5,6])

filter_arr = arr[arr>3]
print(filter_arr)  # 输出: [4 5 6]

[4 5 6]


In [ ]:
# 创建一个二维数组
arr_2d = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

# 筛选所有行，其中第一个元素大于3且第二个元素小于8
# 使用&和括号
filtered_rows = arr_2d[
    (arr_2d[:,0]>3)&
    (arr_2d[:,1]<8)
]
print(filtered_rows)  # 输出: [[4 5 6]]

# 使用numpy的where函数筛选
filtered_rows_where = arr_2d[
    np.where((arr_2d[:,0]>3) & 
    (arr_2d[:,1]<8))
]
print(filtered_rows_where)  # 输出: [[4 5 6]]

# 使用numpy.logical_and函数筛选
filtered_rows_logical_and = arr_2d[
    np.logical_and(arr_2d[:,0]>3, arr_2d[:,1]<8)
]
print(filtered_rows_logical_and)  # 输出: [[4 5 6]]




[[4 5 6]]
[[4 5 6]]
[[4 5 6]]


In [15]:
import numpy as np

# 创建两个矩阵（数组）
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print(matrix1)
print(matrix2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [19]:
import numpy as np

# 创建两个矩阵A和B
# 假设A是2x3的矩阵，B是3x2的矩阵，这样它们就可以相乘了
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

# 使用@符号进行矩阵乘法
C = A @ B
# 或者使用numpy.matmul()函数，效果一样
# C = np.matmul(A, B)

print(C)
# 输出将会是：
# [[ 58  64]
#  [139 154]]
# 这就是A和B“跳舞”后的新队形C

[[ 58  64]
 [139 154]]


In [21]:
import numpy as np

# 创建一个数组
arr = np.array([1, 2, 3, 4, 5, 6])

# 使用 np.where() 找到所有大于3的元素的索引
indices = np.where(arr > 3)
print("Indices of elements greater than 3:", indices)

# 如果你想要基于条件获取实际的元素值
filtered_values = arr[arr > 3]
print("Values greater than 3:", filtered_values)


# 如果你想要同时获取True和False条件下的索引（尽管这在这个场景下可能不常见）
true_indices, false_indices = np.where(arr > 3, [True_indices, False_indices])
# 注意：上面的代码实际上不会按预期工作，因为np.where()不是设计来这样使用的。
# 正确的做法是仅使用condition参数，或者如果你有x和y数组，则使用它们来根据条件替换值。

# 一个更实际的例子，使用x和y来替换值
arr_replaced = np.where(arr > 3, "High", "Low")
print("Replaced array with 'High' and 'Low':", arr_replaced)
# 注意：这里arr_replaced的类型将是'object'，因为NumPy无法推断出所有元素都是字符串

# 对于多维数组
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 找到所有第二列大于5的元素的行索引和列索引
rows, cols = np.where(arr_2d[:, 1] > 5)
print("Rows and cols where second column > 5:", rows, cols)

Indices of elements greater than 3: (array([3, 4, 5], dtype=int64),)
Values greater than 3: [4 5 6]


NameError: name 'True_indices' is not defined

In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.max())

9


In [ ]:
import numpy as np

# 创建一个二维数组，表示三位同学的三门课成绩
arr = np.array([[85, 92, 88], [78, 90, 85], [90, 87, 92]])

# 计算平均值
mean_value = np.mean(arr)
print("平均值:", mean_value)
# 输出: 平均值: 87.44444

# 计算每门课的平均值
mean_per_subject = np.mean(arr, axis=0)
print("每门课的平均值:", mean_per_subject)
# 输出: 每门课的平均值: [84.33 89.67 88.33]

# 计算总和
sum_value = np.sum(arr)
print("总和:", sum_value)
# 输出: 总和: 787

# 计算每门课的总和
sum_per_subject = np.sum(arr, axis=0)
print("每门课的总和:", sum_per_subject)
# 输出: 每门课的总和: [253 269 265]

# 计算累计和
cumsum_value = np.cumsum(arr, axis=1)
print("按行的累计和:\n", cumsum_value)
# 输出:
# [[ 85 177 265]
#  [ 78 168 253]
#  [ 90 177 269]]

# 计算连乘积
prod_all = np.prod(arr)
print("所有成绩的连乘积:", prod_all)
# 输出: 所有成绩的连乘积: 266890240

# 计算每位同学总成绩连乘积
prod_per_student = np.prod(arr, axis=1)
print("每位同学总成绩的连乘积:", prod_per_student)
# 输出: 每位同学总成绩的连乘积: [688160 596700 720360]

# 计算累积积
cumprod_value = np.cumprod(arr, axis=1)
print("按行的累积积:\n", cumprod_value)
# 输出:
# [[  85   7820  687360]
#  [  78   7020  596700]
#  [  90   7830  720360]]

# 计算中位数
median_value = np.median(arr)
print("中位数:", median_value)
# 输出: 中位数: 88.0

# 计算每门课的中位数
median_per_subject = np.median(arr, axis=0)
print("每门课的中位数:", median_per_subject)
# 输出: 每门课的中位数: [85. 90. 88.]

# 计算标准差
std_value = np.std(arr)
print("标准差:", std_value)
# 输出: 标准差: 4.166296279833928

# 计算每门课的标准差
std_per_subject = np.std(arr, axis=0)
print("每门课的标准差:", std_per_subject)
# 输出: 每门课的标准差: [4.92160769 2.05480467 2.86744176]

平均值: 87.44444444444444
每门课的平均值: [84.33333333 89.66666667 88.33333333]
总和: 787
每门课的总和: [253 269 265]
按行的累计和:
 [[ 85 177 265]
 [ 78 168 253]
 [ 90 177 269]]
所有成绩的连乘积: 266890240
每位同学总成绩的连乘积: [688160 596700 720360]
按行的累积积:
 [[    85   7820 688160]
 [    78   7020 596700]
 [    90   7830 720360]]
中位数: 88.0
每门课的中位数: [85. 90. 88.]
标准差: 4.166296279833928
每门课的标准差: [4.92160769 2.05480467 2.86744176]


In [27]:
import numpy as np

# 创建两个数组
array1 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
array2 = np.array([
    [5, 4, 3, 2, 1],
    [10, 9, 8, 7, 6]
])

# 进行数组加法运算
result_array = array1 + array2

# 打印结果，查看加法运算后的数组
print("加法运算结果：\n", result_array)

# 使用np.savetxt保存结果到文本文件
# 假设我们要将结果保存到名为'result.txt'的文件中
np.savetxt("result.txt", result_array, fmt="%d", delimiter=",", newline="\n")

# 注意：fmt参数指定了每个元素的格式，这里是整数'%d'
# delimiter参数指定了元素之间的分隔符，这里是逗号','
# newline参数指定了每行结束后的换行符，这里是换行符'\n'
# 这些参数可以根据需要进行调整

加法运算结果：
 [[ 6  6  6  6  6]
 [16 16 16 16 16]]


In [29]:
np.savetxt(
    "result_with_header.txt",
    result_array,
    fmt="%d",
    delimiter=",",
    header="这是加法运算的结果",
    comments="# ",
)

In [32]:
# 使用loadtxt加载之前保存的数组
# 根据保存时指定的格式和分隔符来加载
loaded_arr = np.loadtxt("result.txt", delimiter=",", dtype=np.int32)

# 如果你保存时没有指定fmt或者delimiter，这里也需要相应地调整
# 比如，如果默认分隔符是空格，且没有指定fmt
# loaded_arr = np.loadtxt('array_data_no_fmt.txt', dtype=float)

# 打印加载的数组来验证
print(loaded_arr)

[[ 6  6  6  6  6]
 [16 16 16 16 16]]
