In [1]:
import numpy as np

# 定义一个矩阵
A = np.array([[1, 2], [3, 4]])

# 计算逆矩阵
A_inv = np.linalg.inv(A)

print("原矩阵 A:")
print(A)
print("逆矩阵 A_inv:")
print(A_inv)

# 验证逆矩阵的性质
I = np.dot(A, A_inv)
print("验证逆矩阵的性质 A * A_inv:")
print(I)

原矩阵 A:
[[1 2]
 [3 4]]
逆矩阵 A_inv:
[[-2.   1. ]
 [ 1.5 -0.5]]
验证逆矩阵的性质 A * A_inv:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [5]:
if np.linalg.det(A) != 0:
    A_inv = np.linalg.inv(A)
else:
    print("矩阵不可逆，无法计算逆矩阵。")

In [6]:
import numpy as np

# 定义一个非方阵或奇异方阵A
A = np.array([[1, 2], [3, 4], [5, 6]])
# 计算伪逆矩阵
A_pinv = np.linalg.pinv(A)

print("原矩阵 A:")
print(A)
print("伪逆矩阵 A_pinv:")
print(A_pinv)

原矩阵 A:
[[1 2]
 [3 4]
 [5 6]]
伪逆矩阵 A_pinv:
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


In [7]:
import numpy as np

# 定义一个矩阵
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 计算矩阵的秩
rank_A = np.linalg.matrix_rank(A)
print("矩阵 A 的秩:", rank_A)

矩阵 A 的秩: 2


In [8]:
import numpy as np

# 创建一个3x3的矩阵
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])

# 计算矩阵的行列式
det = np.linalg.det(matrix)

# 输出结果
print("矩阵:\n", matrix)
print("行列式:", det)

矩阵:
 [[1 2 3]
 [4 5 6]
 [7 8 0]]
行列式: 27.0


In [9]:
import numpy as np

# 定义一个矩阵
A = np.array([[1, 2], [3, 4]])

# 计算矩阵的弗罗贝尼乌斯范数（默认参数即为弗罗贝尼乌斯范数）
norm_A = np.linalg.norm(A)

# 或者显式指定范数为'fro'
norm_A_fro = np.linalg.norm(A, "fro")

# 输出结果
print("矩阵A的弗罗贝尼乌斯范数为:", norm_A)
print("矩阵A的弗罗贝尼乌斯范数（显式指定）为:", norm_A_fro)

# 如果想要计算其他类型的范数（如L1范数或无穷范数），可以修改norm函数的参数
norm_A_1 = np.linalg.norm(A, 1)  # 计算L1范数（列和范数）
norm_A_inf = np.linalg.norm(A, np.inf)  # 计算无穷范数（行和范数）

print("矩阵A的L1范数为:", norm_A_1)
print("矩阵A的无穷范数为:", norm_A_inf)

矩阵A的弗罗贝尼乌斯范数为: 5.477225575051661
矩阵A的弗罗贝尼乌斯范数（显式指定）为: 5.477225575051661
矩阵A的L1范数为: 6.0
矩阵A的无穷范数为: 7.0


In [10]:
import numpy as np


def cramer_rule(A, b):
    """
    使用克拉默法则求解线性方程组 Ax = b
    :param A: 系数矩阵，形状为 (n, n)
    :param b: 常数项向量，形状为 (n,)
    :return: 方程组的解，形状为 (n,)
    """
    n = A.shape[0] # 方程组的未知数个数
    if A.shape[1] != n or b.shape[0] != n:
        raise ValueError("矩阵 A 必须是方阵，向量 b 的长度必须与 A 的行数相同。")

    det_A = np.linalg.det(A)  # 计算系数矩阵的行列式
    if det_A == 0:
        raise ValueError("系数矩阵 A 的行列式为零，方程组无唯一解。")

    x = np.zeros(n)  # 初始化解向量
    for i in range(n):
        # 创建一个新的矩阵，将第 i 列替换为 b
        Ai = np.copy(A) # A.copy()
        Ai[:, i] = b

        # 计算Ai的行列式并除以A的行列式得到解的第i个分量
        x[i] = np.linalg.det(Ai) / det_A

    return x

# 示例使用
A = np.array([[4, 3, 2], [2, -2, 4], [3, 8, 2]])
b = np.array([1, 5, 6])

solution = cramer_rule(A, b)
print("方程组的解为:", solution)

方程组的解为: [-1.44736842  0.71052632  2.32894737]


In [14]:
import numpy as np


def gaussian_elimination(A, b):
    """
    使用高斯消元法求解线性方程组 Ax = b
    :param A: 系数矩阵，形状为 (n, n)
    :param b: 常数项向量，形状为 (n,)
    :return: 方程组的解，形状为 (n,)
    """
    n = A.shape[0]
    if A.shape[1] != n or b.shape[0] != n:
        raise ValueError("系数矩阵A和常数项向量b的维度不匹配")

    # 合并A和b以简化操作
    Ab = np.hstack((A.astype(float), b.reshape(-1, 1).astype(float)))

    # 前向消元过程
    for k in range(n):
        # 选择主元（这里简单起见，不进行部分选主元，实际应用中可能需要）
        # 如果当前行的主元为0，则应该进行行交换（这里省略了行交换的逻辑）

        # 将当前行以下的所有行减去当前行的适当倍数，使得以下行的第k列变为0
        for i in range(k + 1, n):
            factor = Ab[i, k] / Ab[k, k]
            Ab[i, k:] -= factor * Ab[k, k:]

    # 回代过程
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (Ab[i, -1] - np.dot(Ab[i, :i], x[:i])) / Ab[i, i]

    return x


# 示例
A = np.array([[2, 1, -1], [-3, -1, 2], [-2, 1, 2]])
b = np.array([8, -11, -3])

solution = gaussian_elimination(A, b)
print("方程组的解为:", solution)

方程组的解为: [ 4.  2. -1.]


In [15]:
import numpy as np

# 系数矩阵A
A = np.array([[1, 2], [3, 4], [5, 6]])
# 常数项向量b
b = np.array([1, 2, 3])

# 使用lstsq求解最小二乘解
x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)
print("最小二乘解:", x)

最小二乘解: [-1.11274361e-16  5.00000000e-01]


In [16]:
import numpy as np

# 定义一个方阵A
A = np.array([[4, 2], [1, 3]])

# 使用eig函数进行特征值分解
eigenvalues, eigenvectors = np.linalg.eig(A)

# eigenvalues是一个包含特征值的数组
# eigenvectors的列是对应的特征向量

print("特征值：", eigenvalues)
print("特征向量：")
for i, eigenvector in enumerate(eigenvectors.T):
    print(f"特征值 {eigenvalues[i]} 对应的特征向量：{eigenvector}")

# 验证特征值和特征向量的正确性
# 对于每个特征值lambda_i和对应的特征向量v_i，应有 Av_i = lambda_i * v_i
for i, eigenvalue in enumerate(eigenvalues):
    eigenvector = eigenvectors[:, i]
    result = np.dot(A, eigenvector)
    assert np.allclose(result, eigenvalue * eigenvector)
    print(f"验证特征值 {eigenvalue} 和特征向量 {eigenvector} 正确")

特征值： [5. 2.]
特征向量：
特征值 5.0 对应的特征向量：[0.89442719 0.4472136 ]
特征值 2.0 对应的特征向量：[-0.70710678  0.70710678]
验证特征值 5.0 和特征向量 [0.89442719 0.4472136 ] 正确
验证特征值 2.0 和特征向量 [-0.70710678  0.70710678] 正确


In [ ]:
def AHP(A):
    m = len(A)  # 获取指标个数
    n = len(A[0])
    RI = [0, 0, 0.58, 0.90, 1.12, 1.24, 1.32, 1.41, 1.45, 1.49, 1.51]
    R = np.linalg.matrix_rank(A)  # 求判断矩阵的秩
    V, D = np.linalg.eig(A)  # 求判断矩阵的特征值和特征向量，V特征值，D特征向量；
    list1 = list(V)
    B = np.max(list1)  # 最大特征值
    index = list1.index(B)
    C = D[:, index]  # 对应特征向量
    CI = (B - n) / (n - 1)  # 计算一致性检验指标CI
    CR = CI / RI[n]
    if CR < 0.10:
        print("CI=", CI.real)
        print("CR=", CR.real)
        print("对比矩阵A通过一致性检验，各向量权重向量Q为：")
        sum = np.sum(C)
        Q = C / sum  # 特征向量标准化
        print(Q.real)  #    输出权重向量
        return Q.real
    else:
        print("对比矩阵A未通过一致性检验，需对对比矩阵A重新构造")
        return 0

In [17]:
def pca(X, n_components):
    X = np.array(X)
    X = X - np.mean(X)
    n = len(X)
    A = np.dot(X.T, X) / (n - 1)
    V, D = np.linalg.eig(A)
    idx = (-V).argsort(axis=None)[:n_components]
    P = D[idx]
    F = np.dot(X, P.T)
    return V[idx] / sum(V), F

In [26]:
import numpy as np

# 定义一个矩阵A
A = np.array([[1, 2], [3, 4], [5, 6]])

# 使用svd函数进行奇异值分解
U, s, VT = np.linalg.svd(A, full_matrices=False)

# 注意：numpy.linalg.svd返回的s是奇异值数组，而不是对角矩阵
# 我们需要将其转换为对角矩阵形式
Sigma = np.zeros((A.shape[0], A.shape[1]))
Sigma[: len(s), : len(s)] = np.diag(s)

# VT是V的转置，如果需要V，则可以使用VT.T获取
V = VT.T

# 验证SVD的正确性
# A应该等于U * Sigma * VT（注意Sigma不是方阵时，需要按照形状进行乘法）
reconstructed_A = np.dot(U, Sigma)
reconstructed_A = np.dot(reconstructed_A, VT)

# 由于浮点运算的精度问题，我们不会直接比较A和reconstructed_A是否相等
# 而是检查它们是否足够接近
print(np.allclose(A, reconstructed_A))  # 应该输出True或非常接近True的值

# 输出奇异值、左奇异向量和右奇异向量
print("奇异值：", s)
print("左奇异向量：")
print(U)
print("右奇异向量：")
print(V)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)